name: Check Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [main]

jobs:
  getOrCreatePullRequest:
    name: Get Pull Reqest Dev and Release, create if not exist
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request dev details
        id: getPullRequestDev
        uses: actions/github-script@v5
        with:
          script: |
            return github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.repo.pull_number,
            })

      - name: Get pull request release details
        id: getPullRequestRelease
        uses: actions/github-script@v5
        with:
          script: |
            const pullRequestReleases = github.rest.issues.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              pulls: true,
              labels: 'release'
            })
            return pullRequestReleases

      - name: Create pull request release
        if: ${{ steps.getPullRequestRelease.outputs.length == 0 }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Create pull request
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: staging
          delete-branch: true
          title: '[Release] 1.1.0'
          body: |
            ## Fix:
            ## Feature:
            ## Modify:
            ## Breaking:

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            release
          team-reviewers: |
            owners
            maintainers
          draft: true

  checkPullRequestDev:
    name: Check Pull Request Dev
    needs: ['getOrCreatePullRequestRelease']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check pull request dev label
        if: ${{ !contains(fromJSON('["QAPassed"]'), steps.getPullRequestDev.outputs.pr_labels) }}
        run: exit 1

      - name: Check pull request dev title
        uses: actions/github-script@v5
        with:
          script: |
            const prefix = steps.getPullRequestDev.outputs.title.split('-')[0]
            if (!['fix', 'modify', 'feature', 'breaking'].includes(prefix)) {
              exit 1
            }

  checkPullRequestRelease:
    name: Check Pull Request Release
    needs: ['getOrCreatePullRequestRelease']
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request release label
        if: ${{ !contains(fromJSON('["fixStaging"]'), steps.getPullRequestRelease.outputs.pr_labels) }}
        uses: actions/github-script@v5
        with:
          script: |
            if (steps.getPullRequestRelease.labels.includes('lockDeploys')) {
              exit 1
            }

