name: Update Pull Request Release

on:
  push:
    branches: [staging]

jobs:
  update:
    name: update pull request release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: add semver
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Update Pull Request
        uses: actions/github-script@v5
        env:
          TAG_LATEST: ${{ steps.previoustag.outputs.tag }}
          TAG_LATEST_DATE: ${{ steps.previoustag.outputs.timestamp }}
        with:
          script: |
            const script = require('./script/github/updatePullRequest.js')
            script({github, context})
            
